### ISSUE TITLE
[Issue]: Build fails on ROCm 10.x — rocm_smi/rocm_smi.h not found (replaced by amd_smi)

### ISSUE THREAD

**Issue by srinivamd** [ROCm/mori#638]
### Problem Description

Building MORI from source on ROCm 10.x (10.0.0 GA, 10.1.0 nightly) fails with:

```
/root/mori/include/mori/application/topology/gpu.hpp:30:10: fatal error: 'rocm_smi/rocm_smi.h' file not found
   30 | #include "rocm_smi/rocm_smi.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Root Cause

ROCm 10.x replaced `rocm_smi` with `amd_smi`. The header `rocm_smi/rocm_smi.h` no longer ships in the SDK. Three files in MORI still reference the old header:

1. `include/mori/application/topology/gpu.hpp:30`
2. `src/application/topology/gpu.cpp` (uses `rocm_smi` API calls)
3. `include/mori/application/utils/check.hpp`

### Operating System

Ubuntu 24.04

### CPU

AMD EPYC

### GPU

AMD Instinct MI300X (gfx942)

### ROCm Version

10.1.0 (nightly 20260902), also affects 10.0.0 GA

### Steps to Reproduce

```bash
# Inside a ROCm 10.1.0 container with PyTorch base
git clone --branch main https://github.com/ROCm/mori.git
cd mori
pip install Cython "setuptools==83"
python3 -m build --wheel --no-isolation .
# Fails at gpu.hpp:30
```

### Additional Information

Discovered while building the ATOM+AITER+MORI stack docker on ROCm 10.1.0 nightly (0902) base images.

MORI builds fine on ROCm 7.14.0 where `rocm_smi/rocm_smi.h` still exists. The fix would be to update the includes and API calls to use `amd_smi` (the ROCm 10.x replacement), with a compatibility fallback for older ROCm versions if needed.

**Comment by QizhouZhang97** [comment]
Thanks for reporting the issue, I will have a look

**Comment by QizhouZhang97** [comment]
Hi，@srinivamd 
I tried your repro on `rocm/pytorch:rocm10.0_ubuntu24.04_py3.11_pytorch_release_2.13.0`
and couldn't hit it. That image has no `/opt/rocm` at all — ROCm comes from the pip
`rocm-sdk-core` wheel, which ships no CMake configs, so MORI stops much earlier
(`CMakeLists.txt:152`, missing `hip-lang-config.cmake`) and never reaches `gpu.hpp:30`.
After adding the apt stack (`amdrocm-core-dev10.0-gfx950`), `rocm_smi/rocm_smi.h` is
present (191523 bytes) and MORI builds and imports fine alongside torch 2.13.0+rocm10.0.0.

The real ROCm 10 blockers we found are different: ROCm 10's `hsakmt-config.cmake` enables
`find_dependency(NUMA)` but ships no `FindNUMA.cmake`, plus `libdrm-dev` is undeclared.

What's your exact base image name and tag?

**Comment by srinivamd** [comment]
> What's your exact base image name and tag?
That shouldn't matter.

**Comment by srinivamd** [comment]
Closing — investigation shows rocm_smi/rocm_smi.h IS present in our TheRock pip-based docker images at /opt/rocm/include/rocm_smi/rocm_smi.h, and CMake passes -isystem /opt/rocm/include to the compiler. The build failure appears to be in our docker build environment, not a missing header or MORI bug. Apologies for the incorrect report.

**Comment by srinivamd** [comment]
Reopening with evidence of the root cause.

**ROCm/TheRock#6852** ("build: disable rocm-smi-lib build (deprecated)") merged Aug 31, 2026, disables the `rocm_smi_lib` subproject with `-DROCM_SMI_DISABLE=True`. This means `rocm_smi.h` is no longer installed in TheRock builds after that date.

**Evidence from our docker images:**

| Image | `/opt/rocm/include/rocm_smi/` contents |
|---|---|
| 10.0.0 GA (built before Aug 31) | `rocm_smi.h` (191KB), `rocm_smi64Config.h`, `rocm_smi_logger.h` |
| 10.1.0-0902 nightly (built Sep 2) | `rocm_smi_logger.h` only — **`rocm_smi.h` removed** |

MORI's `gpu.hpp:30` and `check.hpp:33` include `rocm_smi/rocm_smi.h` which no longer exists in post-Aug-31 TheRock builds. MORI needs to migrate to the `amd_smi` API, similar to what rocRoller (ROCm/rocm-libraries#8965) and hipBLAS (ROCm/rocm-libraries#8080) already did.
